#!/bin/bash

# Define the name of the environment file you want to use
DEFAULT_ENV_FILE=".env"

create_env_file() {
    echo "Membuat file env: $DEFAULT_ENV_FILE"
    touch "$DEFAULT_ENV_FILE"

    declare -a env_variables=("API_ID" "API_HASH" "BOT_TOKEN" "BOT_NAME" "DEV_NAME")
    for var in "${env_variables[@]}"; do
        read -p "Masukkan $var: " value
        echo "$var=$value" >> "$DEFAULT_ENV_FILE"
    done

    read -p "Apakah file env sudah diisi dengan konfigurasi yang benar? (y/n): " env_configured
    if [ "$env_configured" != "y" ]; then
        rm "$DEFAULT_ENV_FILE"
        create_env_file
    else
        echo "$DEFAULT_ENV_FILE telah dibuat."
        read -p "Apakah Anda ingin menjalankan env yang baru dibuat? (y/n): " run_new_env
        if [ "$run_new_env" == "y" ]; then
            git pull && rm -rf *.session* && python3 chatbot.py "$DEFAULT_ENV_FILE"
            exit 0
        fi
    fi
}

list_env_files() {
    env_files=($(find . -maxdepth 1 -type f -name "*.env" -exec basename {} \;))
    if [ ${#env_files[@]} -eq 0 ]; then
        read -p "Tidak ditemukan file env. Apakah Anda ingin membuatnya sekarang? (y/n): " create_env
        if [ "$create_env" == "y" ]; then
            create_env_file
        else
            echo "Terima kasih. Silakan buat file env kemudian jalankan skrip ini kembali."
            exit 0
        fi
    fi

    echo "Memeriksa keberadaan file env: $DEFAULT_ENV_FILE"
    if [[ ! " ${env_files[@]} " =~ " $DEFAULT_ENV_FILE " ]]; then
        echo "$DEFAULT_ENV_FILE tidak ditemukan. Membuat file baru."
        create_env_file
    else
        echo "$DEFAULT_ENV_FILE ditemukan."
    fi
}

# Check for existing env files and proceed accordingly
list_env_files

# Run the Python script with the specified env file
git pull && rm -rf *.session* && python3 chatbot.py "$DEFAULT_ENV_FILE"
